// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Whitelabel.Infrastructure.Persistence;

#nullable disable

namespace Whitelabel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WhitelabelDbContext))]
    [Migration("20260401192057_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Whitelabel.Infrastructure.Persistence.Entities.ApplicationAdminEntity", b =>
                {
                    b.Property<string>("ObjectId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("ObjectId");

                    b.ToTable("ApplicationAdmins", (string)null);
                });

            modelBuilder.Entity("Whitelabel.Infrastructure.Persistence.Entities.TenantAdminEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ObjectId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("TenantId", "ObjectId");

                    b.ToTable("TenantAdmins", (string)null);
                });

            modelBuilder.Entity("Whitelabel.Infrastructure.Persistence.Entities.TenantEmailDomainEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("TenantEmailDomains", (string)null);
                });

            modelBuilder.Entity("Whitelabel.Infrastructure.Persistence.Entities.TenantEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EntraTenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("Whitelabel.Infrastructure.Persistence.Entities.TenantHostNameEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("HostName")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("TenantHostNames", (string)null);
                });

            modelBuilder.Entity("Whitelabel.Infrastructure.Persistence.Entities.TenantUserGrantEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ObjectId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("TenantId", "ObjectId");

                    b.ToTable("TenantUserGrants", (string)null);
                });

            modelBuilder.Entity("Whitelabel.Infrastructure.Persistence.Entities.TenantAdminEntity", b =>
                {
                    b.HasOne("Whitelabel.Infrastructure.Persistence.Entities.TenantEntity", "Tenant")
                        .WithMany("TenantAdmins")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Whitelabel.Infrastructure.Persistence.Entities.TenantEmailDomainEntity", b =>
                {
                    b.HasOne("Whitelabel.Infrastructure.Persistence.Entities.TenantEntity", "Tenant")
                        .WithMany("EmailDomains")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Whitelabel.Infrastructure.Persistence.Entities.TenantHostNameEntity", b =>
                {
                    b.HasOne("Whitelabel.Infrastructure.Persistence.Entities.TenantEntity", "Tenant")
                        .WithMany("HostNames")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Whitelabel.Infrastructure.Persistence.Entities.TenantUserGrantEntity", b =>
                {
                    b.HasOne("Whitelabel.Infrastructure.Persistence.Entities.TenantEntity", "Tenant")
                        .WithMany("UserGrants")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Whitelabel.Infrastructure.Persistence.Entities.TenantEntity", b =>
                {
                    b.Navigation("EmailDomains");

                    b.Navigation("HostNames");

                    b.Navigation("TenantAdmins");

                    b.Navigation("UserGrants");
                });
#pragma warning restore 612, 618
        }
    }
}
